name: Bug Report
description: Create a report of unintended behavior or problems
body:
  - type: input
    attributes:
        label: Room details
        description: If applicable, provide the room's code and the approximate time you encountered this issue.
        placeholder: (e.g. \#JXQF earlier today at 04:44 AM UTC)
  - type: textarea
    attributes:
        label: Describe the bug/issue
        description: A clear and concise description of what the bug is.
    validations:
        required: true
  - type: textarea
    attributes:
      label: Reproducing
      description: Steps to reproduce the behavior.
      placeholder: |
        1. Go to '...'
        2. Click on '...'
        3. Scroll down to '...'
        4. See error
  - type: textarea
    attributes:
      label: Expected behavior
      description: A clear and concise description of what you expected to happen.
    validations:
      required: true
  - type: textarea
    attributes:
      label: Screenshots
      description: If applicable, add screenshots to help explain your problem.
  - type: textarea
    attributes:
      label: Additional context
      description: Add any other context about the problem here.
